"""Deterministic policy checks before tool dispatch."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path, PureWindowsPath

from hancode.core.actions import Action, ActionType
from hancode.core.config import HanCodeConfig
from hancode.core.models import Phase, TaskStatus
from hancode.policy.path_policy import PathClassifier, PathZone
from hancode.core.phases import build_phase_gate, can_write_artifact
from hancode.core.state import TaskState
from hancode.core.tool_specs import TOOL_SPEC_BY_NAME


_ALLOWED_TOOL_PHASES = {
    spec.name: spec.allowed_phases for spec in TOOL_SPEC_BY_NAME.values()
}
_WRITE_TOOLS = frozenset({"write_file", "edit_file"})
_DETERMINISTIC_DELIVERY_ARTIFACTS = frozenset(
    {"TEST_REPORT.md", "REVIEW.md", "KNOWLEDGE.md", "DELIVERABLES.md"}
)
_SECRET_REQUEST_MARKERS = (
    "api key",
    "apikey",
    "password",
    "token",
    "credential",
    "private key",
    "private_key",
    "secret",
)


def allowed_tools_for_phase(phase: Phase) -> tuple[str, ...]:
    """Return the phase-eligible tool names from the policy's single rule table."""
    return tuple(
        sorted(
            tool_name
            for tool_name, allowed_phases in _ALLOWED_TOOL_PHASES.items()
            if phase in allowed_phases
        )
    )


@dataclass(frozen=True, slots=True)
class PolicyDecision:
    """The deterministic outcome of evaluating an action."""

    allowed: bool
    reason: str
    phase: Phase
    requires_checkpoint: bool = False
    denied_rule: str | None = None
    suggested_fix: str = ""
    target_zone: PathZone | None = None

    def to_dict(self) -> dict[str, object]:
        return {
            "allowed": self.allowed,
            "requires_checkpoint": self.requires_checkpoint,
            "error_code": None if self.allowed else "policy_denied",
            "message": self.reason,
            "phase": self.phase.value,
            "target_zone": None if self.target_zone is None else self.target_zone.value,
            "denied_rule": self.denied_rule,
            "suggested_fix": self.suggested_fix,
        }


class ToolPolicy:
    """Evaluate actions against phase, path, and task-state constraints."""

    def __init__(self, config: HanCodeConfig) -> None:
        self._config = config
        self._path_classifier = PathClassifier(config)

    def evaluate(
        self, *, action: Action, phase: Phase, state: TaskState
    ) -> PolicyDecision:
        if action.phase is not phase:
            return _denied(
                phase,
                "Action phase does not match the current phase.",
                "action_phase_mismatch",
                "Use the current phase in the action.",
            )
        if action.type is ActionType.FINISH_PHASE:
            return self._evaluate_finish_phase(phase, state)
        if action.type is ActionType.ASK_USER:
            return self._evaluate_ask_user(action, phase, state)
        if action.type is ActionType.FINAL:
            return _denied(
                phase,
                "Global completion is controlled by the deterministic router.",
                "final_not_model_selectable",
                "Finish the current phase and let the router determine task completion.",
            )
        if action.type is not ActionType.TOOL_CALL or action.tool_name is None:
            return _denied(
                phase,
                "Action is not an executable tool call.",
                "unsupported_action",
                "Use a supported tool call or control action.",
            )

        if action.tool_name in _WRITE_TOOLS:
            target = action.args.get("path")
            if isinstance(target, str) and _is_clean_relative_path(target):
                if (
                    self._path_classifier.classify(target) is PathZone.ARTIFACT
                    and _artifact_name(target) in _DETERMINISTIC_DELIVERY_ARTIFACTS
                ):
                    return _denied(
                        phase,
                        "This delivery artifact can only be generated by the delivery pipeline.",
                        "deterministic_delivery_artifact",
                        "Use the structured delivery tool or configured test result instead.",
                    )

        allowed_phases = _ALLOWED_TOOL_PHASES.get(action.tool_name)
        if allowed_phases is None or phase not in allowed_phases:
            return _denied(
                phase,
                "Tool is not allowed in the current phase.",
                "tool_not_allowed_in_phase",
                "Choose a tool allowed in the current phase.",
            )
        if action.tool_name == "rollback_last_checkpoint":
            if state.inconsistent or state.status is TaskStatus.INCONSISTENT:
                return _denied(
                    phase,
                    "Rollback requires a consistent task state.",
                    "state_must_be_consistent",
                    "Reconcile task state before requesting rollback.",
                )
            if state.latest_checkpoint is None:
                return _denied(
                    phase,
                    "Rollback requires a committed checkpoint.",
                    "rollback_checkpoint_required",
                    "Create and commit a checkpoint before requesting rollback.",
                )
        if action.tool_name not in _WRITE_TOOLS:
            return _allowed(phase)
        if action.reason is None or not action.reason.strip():
            return _denied(
                phase,
                "Write actions require a reason.",
                "reason_required_for_write",
                "Provide a non-empty reason for the write action.",
            )

        target = action.args.get("path")
        if not isinstance(target, str) or not target.strip():
            return _denied(
                phase,
                "Write actions require a valid target path.",
                "write_path_required",
                "Provide a non-empty relative path.",
            )
        if not _is_clean_relative_path(target):
            return _denied(
                phase,
                "Target path contains unsupported path segments.",
                "path_out_of_scope",
                "Use a clean relative path without dot segments.",
            )
        zone = self._path_classifier.classify(target)
        if zone is PathZone.PROTECTED:
            return _denied(
                phase,
                "Target path is a protected course or credential file.",
                "protected_path",
                "Modify allowed source code instead; do not change course evaluation or credential files.",
            )
        if zone is PathZone.OUT_OF_SCOPE:
            return _denied(
                phase,
                "Target path is outside the writable workspace zones.",
                "path_out_of_scope",
                "Use a configured artifact or source path inside the workspace.",
            )
        if zone is PathZone.ARTIFACT:
            if _artifact_name(target) in _DETERMINISTIC_DELIVERY_ARTIFACTS:
                return _denied(
                    phase,
                    "This delivery artifact can only be generated by the delivery pipeline.",
                    "deterministic_delivery_artifact",
                    "Use the structured delivery tool or configured test result instead.",
                )
            if can_write_artifact(phase, _artifact_name(target)):
                return _allowed(phase, target_zone=PathZone.ARTIFACT)
            return _denied(
                phase,
                "Artifact is not writable in the current phase.",
                "artifact_not_allowed_in_phase",
                "Write the artifact in its designated phase.",
            )
        if zone is PathZone.SOURCE:
            return self._evaluate_source_write(phase, state)
        return _denied(
            phase,
            "Target path is not in a writable zone.",
            "path_out_of_scope",
            "Use a configured artifact or source path inside the workspace.",
        )

    def _evaluate_ask_user(
        self, action: Action, phase: Phase, state: TaskState
    ) -> PolicyDecision:
        if self._config.interaction_mode != "ask_user":
            return _denied(
                phase,
                "Human interaction is disabled by configuration.",
                "interaction_disabled",
                "Set interaction_mode to ask_user before requesting input.",
            )

        question = action.args.get("question")
        if not isinstance(question, str) or not question.strip():
            return _denied(
                phase,
                "ASK_USER requires a non-empty question.",
                "interaction_question_required",
                "Provide one precise non-empty question.",
            )
        if len(question) > self._config.max_interaction_question_chars:
            return _denied(
                phase,
                "ASK_USER question exceeds the configured length limit.",
                "interaction_question_too_long",
                "Shorten the question to the configured character limit.",
            )
        if state.pending_interaction_id is not None:
            return _denied(
                phase,
                "An interaction is already waiting for an answer.",
                "interaction_already_pending",
                "Answer the pending interaction before asking another question.",
            )
        phase_interactions = sum(
            interaction.phase is phase for interaction in state.interactions
        )
        if phase_interactions >= self._config.max_interactions_per_phase:
            return _denied(
                phase,
                "The interaction limit for this phase has been reached.",
                "interaction_limit_exceeded",
                "Continue using the available context instead of asking another question.",
            )
        if _contains_secret_request(question):
            return _denied(
                phase,
                "ASK_USER cannot request credentials or other secrets.",
                "interaction_secret_request_denied",
                "Ask only for non-sensitive project information.",
            )
        return _allowed(phase)

    @staticmethod
    def _evaluate_source_write(phase: Phase, state: TaskState) -> PolicyDecision:
        if state.inconsistent or state.status is TaskStatus.INCONSISTENT:
            return _denied(
                phase,
                "Source writes require a consistent task state.",
                "state_must_be_consistent",
                "Resolve task-state inconsistencies before modifying source files.",
            )
        if phase is not Phase.CODE or state.current_phase is not Phase.CODE:
            return _denied(
                phase,
                "Source writes are only allowed in the code phase.",
                "source_write_requires_code_phase",
                "Return to the code phase before modifying source files.",
            )
        if not state.artifacts["SPEC.md"]:
            return _denied(
                phase,
                "Source writes require SPEC.md.",
                "spec_required_before_source_write",
                "Generate SPEC.md before modifying source files.",
            )
        if not state.artifacts["PLAN.md"]:
            return _denied(
                phase,
                "Source writes require PLAN.md.",
                "plan_required_before_source_write",
                "Generate PLAN.md before modifying source files.",
            )
        return _allowed(
            phase,
            requires_checkpoint=True,
            target_zone=PathZone.SOURCE,
        )

    @staticmethod
    def _evaluate_finish_phase(
        phase: Phase,
        state: TaskState,
    ) -> PolicyDecision:
        gate = build_phase_gate(phase, state)

        if gate.can_finish:
            return _allowed(phase)

        unsatisfied = [
            requirement.description
            for requirement in gate.requirements
            if not requirement.satisfied
        ]

        return _denied(
            phase,
            "Current phase completion requirements are not met.",
            f"{phase.value}_finish_requirements",
            " ".join(unsatisfied),
        )


def _artifact_name(target: str) -> str:
    return target.replace("\\", "/").rsplit("/", 1)[-1]


def _is_clean_relative_path(target: str) -> bool:
    normalized = target.replace("\\", "/")
    path = Path(normalized)
    return (
        not Path(target).is_absolute()
        and not PureWindowsPath(target).is_absolute()
        and not PureWindowsPath(target).drive
        and path.as_posix() == normalized
        and all(part not in {"", ".", ".."} for part in path.parts)
    )


def _contains_secret_request(question: str) -> bool:
    normalized = " ".join(
        question.lower().replace("_", " ").replace("-", " ").split()
    )
    return any(marker in normalized for marker in _SECRET_REQUEST_MARKERS)


def _allowed(
    phase: Phase,
    *,
    requires_checkpoint: bool = False,
    target_zone: PathZone | None = None,
) -> PolicyDecision:
    return PolicyDecision(
        allowed=True,
        reason="Action is allowed.",
        phase=phase,
        requires_checkpoint=requires_checkpoint,
        target_zone=target_zone,
    )


def _denied(
    phase: Phase, reason: str, denied_rule: str, suggested_fix: str
) -> PolicyDecision:
    return PolicyDecision(
        allowed=False,
        reason=reason,
        phase=phase,
        denied_rule=denied_rule,
        suggested_fix=suggested_fix,
    )
